name: dubbuck_front
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^0.8.4+4
  table_calendar: ^3.1.0
  path_provider: ^2.0.11
  get_it: ^7.2.0
  dio: ^4.0.6
  uuid: ^4.3.3
  provider: ^6.1.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  geocoding: ^3.0.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  intl: ^0.19.0
  hive_generator: ^1.1.1
  skeletons: ^0.0.3
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  pull_to_refresh: ^2.0.0
  geolocator: ^11.0.0
  flutter_lints: ^3.0.0
  chat_bubbles: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/브로콜리뚜벅.gif
    - assets/풍속.png
    - assets/습도.png
    - assets/매우좋음.png
    - assets/좋음.png
    - assets/보통.png
    - assets/나쁨.png
    - assets/매우나쁨.png
